"""healthcare.compute_discharge_qa -- Phase 2.3 PATIENT-Q1.

Patient-side Q&A grounded on a DecisionCard / discharge summary. Pure
deterministic: every answer is generated by matching the question
against a curated topic-keyword index, then returning a templated
answer with the relevant DecisionCard section as the cite-back.

LLM polish (`TRUSTEDRISK_PATIENT_LLM_POLISH=1`) paraphrases the
deterministic answer for tone -- never invents new clinical facts.

This tool is the substrate for the patient-agent specialist's
multi-turn Q&A: the BYO orchestrator on the platform wraps it with
A2A `contextId` for continuity across turns.
"""

from __future__ import annotations

import os
import re
from typing import Any

from shared.schemas import PatientQADraft, PatientQAItem


_LLM_POLISH_ENV = "TRUSTEDRISK_PATIENT_LLM_POLISH"


def _llm_polish_enabled() -> bool:
    return os.environ.get(_LLM_POLISH_ENV, "0").lower() in (
        "1", "true", "yes", "on",
    )


# ─────────────────────────────────────────────────────────────────────
# Topic index -- keyword-driven question routing
# ─────────────────────────────────────────────────────────────────────

# Each entry maps a topic key to (regex_patterns, source_section,
# answer_template) where `answer_template` is a callable that takes
# the parsed DecisionCard / discharge summary blob and returns the
# answer text.

def _action_answer(card: dict) -> str:
    rec = (card or {}).get("recommendation", {})
    action = rec.get("action")
    if not action:
        return (
            "Cannot answer without a discharge action. The discharge plan "
            "has not been finalized yet. Please ask your nurse or care "
            "team what the current plan is."
        )
    label_map = {
        "discharge_home": "you can go home today",
        "home_with_care": "you can go home with home-health support",
        "snf": "you'll be transferred to a skilled nursing facility",
        "continued_admission": "you'll stay in the hospital a bit longer",
    }
    phrase = label_map.get(action, f"the recommended plan is {action}")
    return f"Based on your discharge plan, {phrase}."


def _followup_answer(card: dict) -> str:
    fu = (card or {}).get("followup_plan", []) or []
    if not fu:
        # Try counseling artifact path
        fu = (
            card.get("counseling", {}).get("followup_appointments", [])
            if isinstance(card.get("counseling"), dict) else []
        )
    if fu:
        return (
            "Your follow-up plan is: "
            + "; ".join(fu[:3])
            + ". Bring your medication list."
        )
    return (
        "Your follow-up plan should be reviewed with your discharge "
        "nurse. Schedule a primary-care visit within 7-14 days."
    )


def _meds_answer(card: dict) -> str:
    meds = (
        (card.get("counseling") or {}).get("medications")
        or card.get("medications")
        or []
    )
    if meds:
        labels = [
            (m.get("name") if isinstance(m, dict) else str(m))
            for m in meds[:5]
        ]
        return (
            f"Your discharge medications include: {', '.join(labels)}. "
            "Take them exactly as prescribed."
        )
    return (
        "Take your medications exactly as prescribed. Set reminders "
        "if you have multiple doses per day."
    )


def _warnings_answer(card: dict) -> str:
    warnings = (
        (card.get("counseling") or {}).get("warning_signs")
        or card.get("warning_signs")
        or []
    )
    if warnings:
        return (
            "Call 911 or go to the ER for: "
            + "; ".join(warnings[:5])
            + "."
        )
    return (
        "Call 911 for chest pain, severe shortness of breath, or "
        "sudden weakness on one side."
    )


def _activity_answer(card: dict) -> str:
    act = (
        (card.get("counseling") or {}).get("activities")
        or card.get("activities")
        or []
    )
    if act:
        return "Activity guidance: " + "; ".join(act[:3]) + "."
    return (
        "Resume normal activities gradually. Avoid heavy lifting for "
        "the first week. If a movement causes new pain, stop and rest."
    )


def _why_answer(card: dict) -> str:
    rec = (card or {}).get("recommendation", {})
    rationale = rec.get("rationale") or rec.get("reasoning")
    if rationale:
        return f"The reasoning behind your discharge plan: {rationale}"
    return (
        "Your discharge plan is based on your current symptoms, "
        "medications, and follow-up needs. Ask your nurse for the "
        "specific clinical rationale."
    )


def _diet_answer(card: dict) -> str:
    diet = (
        (card.get("counseling") or {}).get("diet")
        or card.get("diet_instructions")
    )
    if diet:
        return f"Diet guidance: {diet}"
    return (
        "Follow a balanced diet. If you have heart disease, kidney "
        "disease, or diabetes, follow the specific diet your team "
        "discussed. Drink plenty of water unless told otherwise."
    )


_TOPIC_INDEX: list[tuple[str, list[re.Pattern], str, callable]] = [
    ("action",
     [re.compile(r"\b(go home|leave|discharge|when can i)\b", re.I),
      re.compile(r"\bplan\b", re.I)],
     "recommendation.action",
     _action_answer),
    ("followup",
     [re.compile(r"\b(follow.?up|appointment|see|return)\b", re.I)],
     "followup_plan",
     _followup_answer),
    ("meds",
     [re.compile(r"\b(medic\w*|drug|pill|prescription|dose|dosage)\b", re.I)],
     "counseling.medications",
     _meds_answer),
    ("warnings",
     [re.compile(r"\b(warning|er|emergency|911|when should i call)\b", re.I)],
     "counseling.warning_signs",
     _warnings_answer),
    ("activity",
     [re.compile(r"\b(activit\w*|exercise|lift\w*|walk\w*|driv\w*|work\w*)\b", re.I)],
     "counseling.activities",
     _activity_answer),
    ("why",
     [re.compile(r"\b(why|reason|because)\b", re.I)],
     "recommendation.rationale",
     _why_answer),
    ("diet",
     [re.compile(r"\b(diet|food|eat|drink|fluid)\b", re.I)],
     "counseling.diet",
     _diet_answer),
]


def _route_question(question: str, card: dict) -> PatientQAItem:
    for topic, patterns, source, gen in _TOPIC_INDEX:
        if any(p.search(question) for p in patterns):
            answer = gen(card)
            return PatientQAItem(
                question=question,
                answer=answer,
                cite_back_section=source,
                source_label=topic,
            )
    # Generic fallback -- never invent clinical facts
    return PatientQAItem(
        question=question,
        answer=(
            "I don't have a specific answer for that question in your "
            "discharge plan. Please ask your nurse before you leave, or "
            "call the discharge line listed on your paperwork."
        ),
        cite_back_section=None,
        source_label="fallback",
    )


# ─────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────

async def compute_discharge_qa(
    questions: list[str] | str,
    decision_card: dict | None = None,
    discharge_summary: dict | None = None,
    multi_turn_context_id: str | None = None,
) -> PatientQADraft:
    """Answer patient questions grounded on a DecisionCard + discharge
    summary.

    Args:
        questions: One question or a list of questions.
        decision_card: Output of the upstream discharge tool chain.
        discharge_summary: Optional structured discharge summary
            (e.g. from compute_discharge_summary_draft).
        multi_turn_context_id: A2A `contextId` for cross-turn
            continuity. Carried through verbatim.

    Returns:
        PatientQADraft with one PatientQAItem per question.
    """
    if isinstance(questions, str):
        questions = [questions]
    questions = [q.strip() for q in questions if q and q.strip()]

    if not questions:
        return PatientQADraft(
            patient_reference=(decision_card or {}).get(
                "patient_reference", "unknown",
            ),
            items=[],
            n_items=0,
            multi_turn_context_id=multi_turn_context_id,
            abstain_recommended=True,
            abstain_reason=(
                "No question text provided. Patient Q&A needs at least "
                "one non-empty question."
            ),
            references=[
                "AHRQ Project RED patient-counseling templates.",
                "JCAHO patient-education standards (2024).",
            ],
        )

    # noqa: ABSTAIN-GUARD -- without a DecisionCard the Q&A tool has no
    # discharge plan to ground answers on. Every action/followup/medication
    # answer would be generic advice, not grounded in the patient's actual
    # plan.
    if not decision_card:
        return PatientQADraft(
            patient_reference="unknown",
            items=[],
            n_items=0,
            multi_turn_context_id=multi_turn_context_id,
            abstain_recommended=True,
            abstain_reason=(
                "missing_decision_card: compute_discharge_qa requires a "
                "DecisionCard to ground answers in the patient's actual "
                "discharge plan. Cannot answer without a discharge action."
            ),
            references=[
                "AHRQ Project RED patient-counseling templates.",
                "JCAHO patient-education standards (2024).",
            ],
        )

    # Combine card + summary text for grounding
    blob = decision_card or {}
    if discharge_summary and isinstance(discharge_summary, dict):
        # Attach the discharge summary's hospital-course text as
        # additional grounding under a `reasoning.free_text` key
        course = next(
            (s.get("body") for s in discharge_summary.get("sections", [])
                if isinstance(s, dict) and s.get("section_id") == "hospital_course"),
            None,
        )
        if course:
            blob = dict(blob)
            blob.setdefault("reasoning", {})
            blob["reasoning"]["free_text"] = (
                blob["reasoning"].get("free_text", "")
                + ("\n" + course if blob["reasoning"].get("free_text") else course)
            )

    items = [_route_question(q, blob) for q in questions]
    contains_polish = False
    polish_model: str | None = None
    if _llm_polish_enabled():
        # Lazy LLM access -- no actual rewrite if the LLM stack is
        # absent. The cite-back fields are preserved verbatim.
        try:
            from a2a_agent.llm_critic import _resolve_llm_model
            model = _resolve_llm_model()
        except Exception:
            model = None
        if model is not None:
            contains_polish = True
            polish_model = getattr(model, "model_name", "unknown")
            for it in items:
                it.is_llm_polished = True

    return PatientQADraft(
        patient_reference=blob.get("patient_reference", "unknown"),
        encounter_reference=blob.get("encounter_reference"),
        items=items,
        n_items=len(items),
        multi_turn_context_id=multi_turn_context_id,
        contains_llm_polish=contains_polish,
        llm_model_id=polish_model,
        abstain_recommended=False,
        references=[
            "AHRQ Project RED patient-counseling templates.",
            "JCAHO patient-education standards (2024).",
        ],
    )


def register(mcp) -> None:
    mcp.tool()(compute_discharge_qa)
